Code/UI/main menu
CakeWithMouse/GameTD pull request #9
Opened 2024-07-02 18:29 UTC by Nekttuman

без дизигна пока

2024-07-02 23:12 UTC, Mysarios requested changes

2024-07-02 23:12 UTC, Mysarios commented on UE_project/Content/UI/MainMenueGameMode.uasset
А шо ето?

2024-07-02 23:12 UTC, Mysarios commented on UE_project/Content/UI/MainMenuGameMode.uasset
И тут не пон шо такое

2024-07-02 23:12 UTC, Mysarios commented on UE_project/Content/Maps/MainMenu.umap
В след раз не пушим мапу пж

2024-07-03 05:41 UTC, Nekttuman commented on UE_project/Content/Maps/MainMenu.umap
поч

2024-07-03 05:41 UTC, Nekttuman commented on UE_project/Content/UI/MainMenueGameMode.uasset
гамемод менюшки

2024-07-03 07:30 UTC, Mysarios approved these changes

2024-07-03 07:30 UTC, merged